/// LOGIN DE USUARIO
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "mail_user": "jumarlinares@gmail.es",
    "password_user": "Admin123"
}


//// TOKEN

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImV4cGlyZXNBdCI6MTY3NTE1NDUzMSwiaWF0IjoxNjcxNTU0NTMxfQ.wOG50YjIPfWQwzCIweqDPRYDHhkZsrTKnZIDFJcaNzM